// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/com/bankledger/protobuf/safe.proto

package com.bankledger.safecoldj;

public final class Safe {
  private Safe() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommonDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bankledger.safegem.CommonData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes version = 1;</code>
     *
     * <pre>
     * 版本
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>required bytes version = 1;</code>
     *
     * <pre>
     * 版本
     * </pre>
     */
    com.google.protobuf.ByteString getVersion();

    /**
     * <code>required bytes assetId = 2;</code>
     *
     * <pre>
     * 资产ID
     * </pre>
     */
    boolean hasAssetId();
    /**
     * <code>required bytes assetId = 2;</code>
     *
     * <pre>
     * 资产ID
     * </pre>
     */
    com.google.protobuf.ByteString getAssetId();

    /**
     * <code>required int64 amount = 3;</code>
     *
     * <pre>
     * 金额
     * </pre>
     */
    boolean hasAmount();
    /**
     * <code>required int64 amount = 3;</code>
     *
     * <pre>
     * 金额
     * </pre>
     */
    long getAmount();

    /**
     * <code>required bytes remarks = 4;</code>
     *
     * <pre>
     * 备注
     * </pre>
     */
    boolean hasRemarks();
    /**
     * <code>required bytes remarks = 4;</code>
     *
     * <pre>
     * 备注
     * </pre>
     */
    com.google.protobuf.ByteString getRemarks();
  }
  /**
   * Protobuf type {@code com.bankledger.safegem.CommonData}
   */
  public static final class CommonData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.bankledger.safegem.CommonData)
      CommonDataOrBuilder {
    // Use CommonData.newBuilder() to construct.
    private CommonData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CommonData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CommonData defaultInstance;
    public static CommonData getDefaultInstance() {
      return defaultInstance;
    }

    public CommonData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CommonData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              version_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              assetId_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              amount_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              remarks_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bankledger.safecoldj.Safe.internal_static_com_bankledger_safegem_CommonData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bankledger.safecoldj.Safe.internal_static_com_bankledger_safegem_CommonData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bankledger.safecoldj.Safe.CommonData.class, com.bankledger.safecoldj.Safe.CommonData.Builder.class);
    }

    public static com.google.protobuf.Parser<CommonData> PARSER =
        new com.google.protobuf.AbstractParser<CommonData>() {
      public CommonData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommonData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CommonData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString version_;
    /**
     * <code>required bytes version = 1;</code>
     *
     * <pre>
     * 版本
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes version = 1;</code>
     *
     * <pre>
     * 版本
     * </pre>
     */
    public com.google.protobuf.ByteString getVersion() {
      return version_;
    }

    public static final int ASSETID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString assetId_;
    /**
     * <code>required bytes assetId = 2;</code>
     *
     * <pre>
     * 资产ID
     * </pre>
     */
    public boolean hasAssetId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes assetId = 2;</code>
     *
     * <pre>
     * 资产ID
     * </pre>
     */
    public com.google.protobuf.ByteString getAssetId() {
      return assetId_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private long amount_;
    /**
     * <code>required int64 amount = 3;</code>
     *
     * <pre>
     * 金额
     * </pre>
     */
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 amount = 3;</code>
     *
     * <pre>
     * 金额
     * </pre>
     */
    public long getAmount() {
      return amount_;
    }

    public static final int REMARKS_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString remarks_;
    /**
     * <code>required bytes remarks = 4;</code>
     *
     * <pre>
     * 备注
     * </pre>
     */
    public boolean hasRemarks() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes remarks = 4;</code>
     *
     * <pre>
     * 备注
     * </pre>
     */
    public com.google.protobuf.ByteString getRemarks() {
      return remarks_;
    }

    private void initFields() {
      version_ = com.google.protobuf.ByteString.EMPTY;
      assetId_ = com.google.protobuf.ByteString.EMPTY;
      amount_ = 0L;
      remarks_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAssetId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRemarks()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, assetId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, amount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, remarks_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, assetId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, amount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, remarks_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bankledger.safecoldj.Safe.CommonData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bankledger.safecoldj.Safe.CommonData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bankledger.safecoldj.Safe.CommonData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bankledger.safecoldj.Safe.CommonData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bankledger.safecoldj.Safe.CommonData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bankledger.safecoldj.Safe.CommonData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bankledger.safecoldj.Safe.CommonData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bankledger.safecoldj.Safe.CommonData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bankledger.safecoldj.Safe.CommonData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bankledger.safecoldj.Safe.CommonData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bankledger.safecoldj.Safe.CommonData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bankledger.safegem.CommonData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bankledger.safegem.CommonData)
        com.bankledger.safecoldj.Safe.CommonDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bankledger.safecoldj.Safe.internal_static_com_bankledger_safegem_CommonData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bankledger.safecoldj.Safe.internal_static_com_bankledger_safegem_CommonData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bankledger.safecoldj.Safe.CommonData.class, com.bankledger.safecoldj.Safe.CommonData.Builder.class);
      }

      // Construct using com.bankledger.safecoldj.Safe.CommonData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        assetId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        amount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        remarks_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bankledger.safecoldj.Safe.internal_static_com_bankledger_safegem_CommonData_descriptor;
      }

      public com.bankledger.safecoldj.Safe.CommonData getDefaultInstanceForType() {
        return com.bankledger.safecoldj.Safe.CommonData.getDefaultInstance();
      }

      public com.bankledger.safecoldj.Safe.CommonData build() {
        com.bankledger.safecoldj.Safe.CommonData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bankledger.safecoldj.Safe.CommonData buildPartial() {
        com.bankledger.safecoldj.Safe.CommonData result = new com.bankledger.safecoldj.Safe.CommonData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.assetId_ = assetId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.amount_ = amount_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.remarks_ = remarks_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bankledger.safecoldj.Safe.CommonData) {
          return mergeFrom((com.bankledger.safecoldj.Safe.CommonData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bankledger.safecoldj.Safe.CommonData other) {
        if (other == com.bankledger.safecoldj.Safe.CommonData.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasAssetId()) {
          setAssetId(other.getAssetId());
        }
        if (other.hasAmount()) {
          setAmount(other.getAmount());
        }
        if (other.hasRemarks()) {
          setRemarks(other.getRemarks());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasAssetId()) {
          
          return false;
        }
        if (!hasAmount()) {
          
          return false;
        }
        if (!hasRemarks()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bankledger.safecoldj.Safe.CommonData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bankledger.safecoldj.Safe.CommonData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString version_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes version = 1;</code>
       *
       * <pre>
       * 版本
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes version = 1;</code>
       *
       * <pre>
       * 版本
       * </pre>
       */
      public com.google.protobuf.ByteString getVersion() {
        return version_;
      }
      /**
       * <code>required bytes version = 1;</code>
       *
       * <pre>
       * 版本
       * </pre>
       */
      public Builder setVersion(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes version = 1;</code>
       *
       * <pre>
       * 版本
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString assetId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes assetId = 2;</code>
       *
       * <pre>
       * 资产ID
       * </pre>
       */
      public boolean hasAssetId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes assetId = 2;</code>
       *
       * <pre>
       * 资产ID
       * </pre>
       */
      public com.google.protobuf.ByteString getAssetId() {
        return assetId_;
      }
      /**
       * <code>required bytes assetId = 2;</code>
       *
       * <pre>
       * 资产ID
       * </pre>
       */
      public Builder setAssetId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        assetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes assetId = 2;</code>
       *
       * <pre>
       * 资产ID
       * </pre>
       */
      public Builder clearAssetId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        assetId_ = getDefaultInstance().getAssetId();
        onChanged();
        return this;
      }

      private long amount_ ;
      /**
       * <code>required int64 amount = 3;</code>
       *
       * <pre>
       * 金额
       * </pre>
       */
      public boolean hasAmount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 amount = 3;</code>
       *
       * <pre>
       * 金额
       * </pre>
       */
      public long getAmount() {
        return amount_;
      }
      /**
       * <code>required int64 amount = 3;</code>
       *
       * <pre>
       * 金额
       * </pre>
       */
      public Builder setAmount(long value) {
        bitField0_ |= 0x00000004;
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 amount = 3;</code>
       *
       * <pre>
       * 金额
       * </pre>
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        amount_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString remarks_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes remarks = 4;</code>
       *
       * <pre>
       * 备注
       * </pre>
       */
      public boolean hasRemarks() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes remarks = 4;</code>
       *
       * <pre>
       * 备注
       * </pre>
       */
      public com.google.protobuf.ByteString getRemarks() {
        return remarks_;
      }
      /**
       * <code>required bytes remarks = 4;</code>
       *
       * <pre>
       * 备注
       * </pre>
       */
      public Builder setRemarks(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        remarks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes remarks = 4;</code>
       *
       * <pre>
       * 备注
       * </pre>
       */
      public Builder clearRemarks() {
        bitField0_ = (bitField0_ & ~0x00000008);
        remarks_ = getDefaultInstance().getRemarks();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.bankledger.safegem.CommonData)
    }

    static {
      defaultInstance = new CommonData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.bankledger.safegem.CommonData)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bankledger_safegem_CommonData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bankledger_safegem_CommonData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,main/java/com/bankledger/protobuf/safe" +
      ".proto\022\026com.bankledger.safegem\"O\n\nCommon" +
      "Data\022\017\n\007version\030\001 \002(\014\022\017\n\007assetId\030\002 \002(\014\022\016" +
      "\n\006amount\030\003 \002(\003\022\017\n\007remarks\030\004 \002(\014B \n\030com.b" +
      "ankledger.safecoldjB\004Safe"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_bankledger_safegem_CommonData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bankledger_safegem_CommonData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bankledger_safegem_CommonData_descriptor,
        new java.lang.String[] { "Version", "AssetId", "Amount", "Remarks", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
